fixed missing BOOST dep:
    g++ -c -o ./out/linuxx86/debug/plugins/component/entity/move/viewbob/viewbob.o -I. -I./include -I./src -I. -Wall -Wno-unknown-pragmas -g -O1 -fPIC -g -O1 -fPIC -g3 -DCS_DEBUG -fPIC -I/home/peragro/build/peragro/extlibs/cs/include -I/home/peragro/build/peragro/extlibs/cel/include  plugins/component/entity/move/viewbob/viewbob.cpp

In file included from plugins/component/entity/move/viewbob/viewbob.cpp:34:
./src/client/event/eventmanager.h:41:32: error: boost/shared_ptr.hpp: No such file or directory